arrowParens: avoid
bracketSpacing: false
trailingComma: none
tabWidth: 2
semi: false
quoteProps: consistent
importOrder:
  - "^(\\./|\\.\\./)"
importOrderSeparation: true
importOrderSortSpecifiers: true
#plugins:
#  - prettier-plugin-import-sort
overrides:
  - files:
      - "*.ts"
      - "*.tsx"
    options:
      parser: typescript
