version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:16.16
    resource_class: small
jobs:
  install-deps:
    executor: node
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --freeze-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint via ESLint and Prettier
          command: yarn lint
  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish
          command: NPM_AUTH_TOKEN=$AUTH_TOKEN yarn publish --no-git-tag-version --registry $REGISTRY
  github-release:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Generate GitHub Release
          command: yarn conventional-github-releaser --token $GITHUB_TOKEN --preset custom-config
workflows:
  lint-deploy:
    jobs:
      - install-deps:
          filters: &tags-filters
            tags:
              only: /^v\d+\.\d+\.\d+.*/
      - lint:
          filters:
            <<: *tags-filters
          requires:
            - install-deps
      - build:
          filters: &version-filters
            <<: *tags-filters
            branches:
              ignore: /.*/
          requires:
            - lint
      - github-release:
          filters:
            <<: *version-filters
          requires:
            - lint
          context:
            - conventional-github-releaser
      - publish:
          filters:
            <<: *version-filters
          requires:
            - build
          context:
            - npm-registry
